WinForms/InventoryProject(Validation is done)/InventoryProject/Controllers/HomeController.cs
using InventoryProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Security.Cryptography.X509Certificates;
using System.Net.Security;

namespace InventoryProject.Controllers
{
    public class HomeController : Controller
    {
        InventoryContext Db = new InventoryContext();
        public ActionResult Index()
        {
           // Db.Category.Add(new Category { CategoryName = "Mobile" });
           // Db.SaveChanges();
          
            return View();
        }

        public JsonResult IsProductCodeExists(int ProductCode)
        {
            //check if any of the UserName matches the UserName specified in the Parameter using the ANY extension method.  
            return Json(!Db.Product.Any(x => x.ProductCode == ProductCode), JsonRequestBehavior.AllowGet);
        }
        public JsonResult ProductName(string ProductName)
        {
            //check if any of the UserName matches the UserName specified in the Parameter using the ANY extension method.  
            return Json(!Db.Product.Any(x => x.ProductName == ProductName), JsonRequestBehavior.AllowGet);
        }
        

        public ActionResult Add()
        {
           
            return View();
        }
        public ActionResult Sales()
        {
            return View();
        }
        public ActionResult Contact()
        {

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Contact(MVCEmail model)
        {
            if (ModelState.IsValid)
            {
                var body = "<p>Email From: itsupport ({1})</p><p>Message:</p><p></p>";
                var message = new MailMessage();
                message.To.Add(new MailAddress("Aamod0611@gmail.com"));  // replace with valid value 
                message.From = new MailAddress("itsupport@creativecapsule.com");  // replace with valid value
                message.Subject = "Require stock ";
                message.Body =body;
                message.IsBodyHtml = true;

                ServicePointManager.ServerCertificateValidationCallback =
    delegate (object s, X509Certificate certificate,
             X509Chain chain, SslPolicyErrors sslPolicyErrors)
    { return true; };


                using (var smtp = new SmtpClient())
                {
                    var credential = new NetworkCredential
                    {
                        UserName = "user@outlook.com",  // replace with valid value
                        Password = "password"  // replace with valid value
                    };
                    smtp.Credentials = credential;
                    smtp.Host = "zuari.creativecapsule.local";
                    smtp.Port = 25;
                    smtp.EnableSsl = true;
                    await smtp.SendMailAsync(message);
                    return RedirectToAction("Sent");
                }
            }
            return View(model);
        }

        public ActionResult PostSalesProduct(OrderItem data)
        {
            Product p = Db.Product.Where(x => x.ProductID == data.ProductID).Single();

            if (data.OrderQuantity < p.QtyInStock)
            {
                p.QtyInStock = p.QtyInStock - data.OrderQuantity;
                Db.OrderItem.Add(new OrderItem { Rate = data.Rate, OrderQuantity = data.OrderQuantity, ProductID = data.ProductID, CategoryID = data.CategoryID });
                if(p.QtyInStock< p.ReOrderLevel)
                {
                    Db.SaveChanges();
                    return RedirectToAction("Contact");
                }
                Db.SaveChanges();
            }
            else
            {
                return RedirectToAction("QuantityNotFound");
            }
            return View();
        }
        public ActionResult QuantityNotFound()
        {
            return View();
        }

        public ActionResult Sent()
        {
            return View();
        }
    }
}

WinForms/InventoryProject(Validation is done)/InventoryProject/Controllers/InventoryApiController.cs
using InventoryProject.Models;
using InventoryProject.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mail;
using System.Net.Security;
using System.Security.Cryptography.X509Certificates;
using System.Web.Http;
using System.Web.Http.Results;

namespace InventoryProject.Controllers
{
    [RoutePrefix("api/InventoryApi")]
    public class InventoryApiController : ApiController
    {
        InventoryContext Db = new InventoryContext();
        Product products = new Product();
        [HttpGet]
        [Route("GetProduct")]
        public IEnumerable<Product> GetProduct()
        {

            return Db.Product.ToList();

        }

        



        [HttpDelete]
        public void DeleteDetail(int id)
        {

            var del = Db.Product.First(x => x.ProductID == id);
            Db.Product.Remove(del);
            Db.SaveChanges();

        }

        [HttpPost]
        [Route("PostData")]
        public void PostData([FromBody]Product data)
        {
            if (ModelState.IsValid)
            {
                Db.Product.Add(new Product { CategoryID = data.CategoryID, ProductCode = data.ProductCode, ProductName = data.ProductName, IsDiscontinuedID = data.IsDiscontinuedID, UnitPrice = data.UnitPrice, QtyInStock = data.QtyInStock, ReOrderLevel = data.ReOrderLevel });
                Db.SaveChanges();
            }
        }

        [HttpPut]
        public void EditDetails(int Id, [FromBody]string data)
        {

            var EditValue = Db.Product.First(x => x.ProductID == Id);
            EditValue.ProductName = data;
            Db.SaveChanges();

        }


        [HttpGet]
        [Route("GetCategory")]
        public IEnumerable<Category> GetCategory()
        {
   
            return Db.Category.ToList();

        }

        [HttpGet]
        [Route("GetIsDiscontinued")]
        public IEnumerable<IsDiscontinued> GetIsDiscontinued()
        {

            return Db.IsDiscontinued.ToList();

        }



        [HttpGet]
        [Route("GetProductList")]
        public IEnumerable<Product> GetProductList(int Prodvalue)
        {
            var ProdList = Db.Product.Where(c => c.CategoryID == Prodvalue);
            return ProdList;

        }
        [HttpGet]
        [Route("GetQuantity")]
        public int GetQuantity(int id)
        {
            int quantity = Db.Product.Where(c => c.ProductID == id).Select(x=>x.QtyInStock).Single();
            return quantity;

        }




        [HttpPost]
        [Route("PostSalesData")]
        public async void PostSalesData([FromBody]OrderItem data)
        {
            if (ModelState.IsValid)
            {
                //ProductQuantity Vm = new ProductQuantity();
                Product p = Db.Product.Where(x => x.ProductID == data.ProductID).Single();
                p.QtyInStock = p.QtyInStock - data.OrderQuantity;
                Db.OrderItem.Add(new OrderItem { Rate = data.Rate, OrderQuantity = data.OrderQuantity, ProductID = data.ProductID, CategoryID = data.CategoryID });
                if (p.QtyInStock < p.ReOrderLevel)
                {
                    Db.SaveChanges();

                    var body = "<p>Email From: itsupport (itsupport@creativecapsule.com)</p><p>Message: I want more product</p><p></p>";
                    var message = new MailMessage();
                    message.To.Add(new MailAddress("Aamod0611@gmail.com"));  // replace with valid value 
                    message.From = new MailAddress("itsupport@creativecapsule.com");  // replace with valid value
                    message.Subject = "Require stock ";
                    message.Body = body;
                    message.IsBodyHtml = true;

                    ServicePointManager.ServerCertificateValidationCallback =
                    delegate (object s, X509Certificate certificate,
                     X509Chain chain, SslPolicyErrors sslPolicyErrors)
                   { return true; };


                    using (var smtp = new SmtpClient())
                    {
                        var credential = new NetworkCredential
                        {
                            UserName = "user@outlook.com",  // replace with valid value
                            Password = "password"  // replace with valid value
                        };
                        smtp.Credentials = credential;
                        smtp.Host = "zuari.creativecapsule.local";
                        smtp.Port = 25;
                        smtp.EnableSsl = true;
                        await smtp.SendMailAsync(message);

                    }

                }
                Db.SaveChanges();

            }
        }
       }
    }

WinForms/InventoryProject(Validation is done)/InventoryProject/Views/Home/Add.cshtml
@model  InventoryProject.Models.Product
@{
    ViewBag.Title = "Index";
}


<div class="container">
    <h2>Login Form</h2>
    @using (Html.BeginForm("Index", "Home", FormMethod.Post))
    {
        <input type="hidden" id="Empid" name="empid" />

        <div class="form-group">
            @Html.LabelFor(m => m.ProductCode)
            @Html.TextBoxFor(m => m.ProductCode, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.ProductCode)
        </div>

            @*<div class="form-group">
                <label for="ProductCode">Product Code:</label>
                <input type="text" class="form-control" id="ProductCode" placeholder="Enter ProductCode">
            </div>*@

            <div class="form-group">
                @Html.LabelFor(m => m.ProductName)
                @Html.TextBoxFor(m => m.ProductName, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.ProductName)
            </div>

            @*<div class="form-group">
                <label for="ProductName">Product Name:</label>
                <input type="text" class="form-control" id="ProductName" placeholder="Enter ProductName">
            </div>*@

            <div>
                <label>Select Categories :</label>
                <select class="form-control" id="CategoryID">
                    <option selected="selected">Select</option>
                </select>
            </div>



            <div class="form-group">
                @Html.LabelFor(m => m.UnitPrice)
                @Html.TextBoxFor(m => m.UnitPrice, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.UnitPrice)
            </div>
            @*<div class="form-group">
                <label for="UnitPrice">UnitPrice:</label>
                <input type="text" class="form-control" id="UnitPrice" placeholder="Enter UnitPrice">
            </div>*@


            <div class="form-group">
                @Html.LabelFor(m => m.QtyInStock)
                @Html.TextBoxFor(m => m.QtyInStock, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.QtyInStock)
            </div>
            @*<div class="form-group">
                <label for="QtyInStock">QtyInStock:</label>
                <input type="text" class="form-control" id="QtyInStock" placeholder="Enter QtyInStock">
            </div>*@



          <div>
            <label>Select IsDiscontinued :</label>
            <select class="form-control" id="IsDiscontinuedID">
                <option selected="selected">Select</option>
            </select>
          </div>

            @*<div class="form-group">
                <label for="IsDiscontinued">IsDiscontinued:</label>
                <input type="text" class="form-control" id="IsDiscontinued" placeholder="Enter IsDiscontinued">
            </div>*@



            <div class="form-group">
                @Html.LabelFor(m => m.ReOrderLevel)
                @Html.TextBoxFor(m => m.ReOrderLevel, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.ReOrderLevel)
            </div>
            @*<div class="form-group">
                <label for="ReOrderLevel">ReOrderLevel:</label>
                <input type="text" class="form-control" id="ReOrderLevel" placeholder="Enter ReOrderLevel">
            </div>*@



        <button type="Submit" class="btn btn-default" onclick="add_details()">Submit</button>


    }
</div>


    <div style="text-align:center; margin-top: 50px;">
        <div class="row">
            <div class="col-sm-12">
                <ul id="listdata">

                </ul>
            </div>
            <input type="hidden" name="ID" id="hiddenID" value="">
        </div>
    </div>
   




<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script type="text/javascript">

    $(document).ready(function () {
       // alert("bomm")
        $.ajax({

            type: "GET",
            url: "http://localhost:62045/api/inventoryapi/GetProduct", //URI

            dataType: "json",
            success: function (data) {
                debugger;
                var datavalue = data;
                var myJsonObject = datavalue;
                contentType: "application/json";

                $.each(myJsonObject, function (i, mobj) {
                    $("#listdata").append('<li style="text-align: left;border: 1px solid gainsboro;padding: 10px;">' + mobj.ProductName + "<input  type='button' id='Remove'  value='Remove' onclick='removeitem(" + mobj.ProductID + ")'/>" + "<input type='button' id='Update' value='Update' value='Update' onclick='update_details(" + mobj.ProductID + ")'/>" + "<input type='button' id='Edit' value='Edit' id='edit' onclick='EditDetails(" + mobj.ProductID + "," + mobj.ProductCode + ",\"" + mobj.ProductName + "\"," + mobj.UnitPrice + "," + mobj.QtyInStock + "," + mobj.ReOrderLevel + ",\"" + mobj.IsDiscontinued + "\")'/>" + '</li>');

                });

            },
            error: function (xhr) {
                alert(xhr.responseText);
            }
        });

    });



    $(document).ready(function () {
       // alert("discon")
        $.ajax({

            type: "GET",
            url: "http://localhost:62045/api/inventoryapi/GetIsDiscontinued", //URI

            dataType: "json",
            success: function (data) {
                debugger;
                var datavalue = data;
                var myJsonObject = datavalue;
                contentType: "application/json";

                $.each(myJsonObject, function (i, mobj) {
                    $("#IsDiscontinuedID").append('<option value="' + mobj.IsDiscontinuedID + '">' + mobj.IsDiscontinuedOptions + '</option>');

                });

            },
            error: function (xhr) {
                alert(xhr.responseText);
            }
        });

    });


















    function removeitem(id) //you are passing id from database using click function
    {
       // alert("baba")
        $.ajax({
            type: "DELETE",
            url: "@Url.Action("DeleteDetail", "api/InventoryApi")" + "/" + id,// "http://localhost:62045/api/inventoryapi/DeleteDetail" + "/" + ProductID,
        });
        //alert("hi");
    }

    function add_details()
        {
            $.ajax({
                type: "post", //http post method
                url: "http://localhost:62045/api/inventoryapi/PostData",
                data: { //passing data
                    ProductCode: $("#ProductCode").val(), //Reading text box values using Jquery
                    ProductName: $("#ProductName").val(),
                    CategoryID: $("#CategoryID").val(),
                    UnitPrice: $("#UnitPrice").val(),
                    QtyInStock: $("#QtyInStock").val(),
                    IsDiscontinuedID: $("#IsDiscontinuedID").val(),
                    ReOrderLevel: $("#ReOrderLevel").val()
                },

            });
          //  alert("hi");
    }


    function EditDetails(Id, ProductCode, ProductName, UnitPrice, QtyInStock, ReOrderLevel, IsDiscontinued) {
        $('#ProductCode').val(ProductCode);
        $('#ProductName').val(ProductName);
        $('#CategoryID').val(CategoryID);
        $('#UnitPrice').val(UnitPrice);
        $('#QtyInStock').val(QtyInStock);
        $('#IsDiscontinued').val(IsDiscontinued);
        $('#ReOrderLevel').val(ReOrderLevel);

        document.getElementById("hiddenID").value = Id;
    }

    function update_details(id) {
        
            var ProductName = JSON.stringify(document.getElementById('ProductName').value);
            var UnitPrice = JSON.stringify(document.getElementById('UnitPrice').value);
            var ProductCode = JSON.stringify(document.getElementById('ProductCode').value);
            var QtyInStock = JSON.stringify(document.getElementById('QtyInStock').value);
            var IsDiscontinued = JSON.stringify(document.getElementById('IsDiscontinued').value);
            var ReOrderLevel = JSON.stringify(document.getElementById('ReOrderLevel').value);
        
        var Id = document.getElementById("hiddenID").value;

        $.ajax({
            type: "PUT", //HTTP Put Method
            url:  "@Url.Action("EditDetails", "api/InventoryApi")" + "/" + id,
            contentType: "application/json; charset=utf-8",
            data: ProductName,
            dataType: JSON,

        });
       // alert("hello");
    }




    $(document).ready(function () {
        debugger;

        @*$.get("@Url.Action("GetCategory", "InventoryApi")", function () {
            alert("success");
        })*@
        //alert("kl")
        $.ajax({
            type: "GET",
            url: "@Url.Action("GetCategory", "api/InventoryApi")",//"http://localhost:62045/api/InventoryApi/GetCategory", //URI

            //dataType: "json",
            success: function (data) {
                     //  alert(data);

                     debugger;
                     var datavalue = data;
                     var myJsonObject = datavalue;
                     contentType: "application/json";
                // alert(datavalue);
                // alert(myJsonObject);

                $.each(myJsonObject, function (i, mobj) {
          //          alert(mobj.CategoryID);
                    $("#CategoryID").append('<option value="' + mobj.CategoryID + '">' + mobj.CategoryName +  '</option>');

                     });

                 },
            error: function (xhr) {
                     alert(xhr.responseText);
                 }
             });

    });



</script>

WinForms/InventoryProject(Validation is done)/InventoryProject/Views/Home/Contact.cshtml
@model InventoryProject.Models.MVCEmail
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("Contact","Home",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <h4>Send your comments.</h4>
    <hr />
    <div class="form-group">
        @Html.LabelFor(m => m.FromName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.FromName, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.FromName)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.FromEmail, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.FromEmail, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.FromEmail)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Message, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextAreaFor(m => m.Message, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Message)
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Send" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WinForms/InventoryProject(Validation is done)/InventoryProject/Views/Home/Index.cshtml
<div class="Operations" style="text-align: center;border:1px solid ; margin: 73px 280px;padding: 50px;">
    <div class="container">
        <div class="row">
            <button type="button" onclick="location.href='@Url.Action("Add", "Home")'" style="font-size: 25px;padding: 25px 94px">Add</button>
        </div>
        <div class="row">
            <button type="button" onclick="location.href='@Url.Action("Sales", "Home")'" style="font-size: 25px;padding: 25px 85px;margin-top: 30px;">Sales</button>
        </div>
    </div>
</div>

WinForms/InventoryProject(Validation is done)/InventoryProject/Views/Home/QuantityNotFound.cshtml
@{
    ViewBag.Title = "QuantityNotFound";
}

<h2>Quantity Not Found</h2>

WinForms/InventoryProject(Validation is done)/InventoryProject/Views/Home/Sales.cshtml
@model InventoryProject.Models.OrderItem

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

<script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>

<script src="//ajax.aspnetcdn.com/ajax/mvc/4.0/jquery.validate.unobtrusive.min.js"></script>


@using (Html.BeginForm("Sales", "Home", FormMethod.Post))
{
<div>
    <label>Select Categories :</label>
    <select class="form-control qunt" id="CategoryID" onchange="FillProduct()">
        <option selected="selected">Select</option>
        @Html.ValidationMessageFor(m => m.CategoryID)
    </select>
</div>

<div>
    <label>Select Product :</label>
    <select class="form-control qunt" id="Product">
        <option selected="selected">Select</option>
    </select>
</div>

<div class="form-group">
    @Html.LabelFor(m => m.OrderQuantity)
    <input type="number" class="form-control " id="OrderQuantity" placeholder="Enter OrderQuantity" min="1" onkeydown="return false">
    <div id="quantity" class="hidden"></div>
    @Html.ValidationMessageFor(m => m.OrderQuantity)
</div>

<div class="form-group">
        @Html.LabelFor(m => m.Rate)
        @Html.TextBoxFor(m => m.Rate, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Rate)
</div>







@*<div class="form-group">
    <label for="Rate">Rate:</label>
    <input name="Rate" type="text" class="form-control text-box single-line" id="Rate" placeholder="Enter Rate" data-val="true" data-val-length="The field LastName must be a string with a maximum length of 50." data-val-length-max="50" data-val-required="The LastName field is required.">
    @Html.ValidationMessageFor(model => model.Rate)
</div>*@

<button type="Submit" class="btn btn-default" onclick="add_details()">Submit</button>

}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script type="text/javascript">



    $(function () {
        $(".qunt").click(function () {
            //alert("laglo")
            $("#OrderQuantity").val(function () { return true });
        });
});




    function add_details() {
        $.ajax({
            type: "post", //http post method
            url: "http://localhost:62045/api/InventoryApi/PostSalesData",
            data: { //passing data
                CategoryID: $("#CategoryID").val(), //Reading text box values using Jquery
                ProductID: $("#Product").val(),
                OrderQuantity: $("#OrderQuantity").val(),
                Rate: $("#Rate").val(),
            },
            //success: function (data) {
            //    alert(QtyInStock)
            //    alert(p.QtyInStock)
            //    var datavalue = data;
            //    var myJsonObject = datavalue;
            //    contentType: "application/json";
            //    $.each(myJsonObject, function (i, mobj) {
            //        alert(mobj.QtyInStock)
            //        $("#quantity").append("stock = ",mobj.QtyInStock);
                });



       }


$(document).ready(function () {
        debugger;

@*$.get("@Url.Action("GetCategory", "InventoryApi")", function () {
        alert("success");
    })*@
      //  alert("kl")
        $.ajax({
            type: "GET",
            url: "@Url.Action("GetCategory", "api/InventoryApi")",//"http://localhost:62045/api/InventoryApi/GetCategory", //URI

            //dataType: "json",
            success: function (data) {
            //  alert(data);

            debugger;
            var datavalue = data;
            var myJsonObject = datavalue;
            contentType: "application/json";
            // alert(datavalue);
            // alert(myJsonObject);

            $.each(myJsonObject, function (i, mobj) {
          //  alert(mobj.CategoryID);
            $("#CategoryID").append('<option value="' + mobj.CategoryID + '">' + mobj.CategoryName +  '</option>');

            });

            },
            error: function (xhr) {
            alert(xhr.responseText);
            }
    });

});



    //$(document).ready(function () {
    //    debugger;

    @*$.get("@Url.Action("GetCategory", "InventoryApi")", function () {
    alert("success");
})*@
    function FillProduct() {
        var CatValue = $('#CategoryID').val();
       // alert(CatValue)
        $.ajax({
            type: "GET",
            url: "@Url.Action("GetProductList", "api/InventoryApi")",//"http://localhost:62045/api/InventoryApi/GetCategory", //URI
            data: { Prodvalue : CatValue },
        //dataType: "json",
        success: function (data) {
            //  alert(data);

            debugger;
            var datavalue = data;
            var myJsonObject = datavalue;
            contentType: "application/json";
            // alert(datavalue);
            // alert(myJsonObject);
            $("#Product").html("");
            $.each(myJsonObject, function (i, mobj) {
                alert(mobj.ProductName);
                $("#Product").append('<option value="' + mobj.ProductID + '">' + mobj.ProductName + '</option>');

            });

        },
        error: function (xhr) {
            alert(xhr.responseText);
        }
    });

    }

    //used this get method to get apropriate no of stock
    $("#Product").blur(function () {
    $.ajax({
        type: "GET",
        url: "@Url.Action("GetQuantity", "api/InventoryApi")",//"http://localhost:62045/api/InventoryApi/GetCategory", //URI
        data: { id: $("#Product").val() },
        //dataType: "json",
        success: function (data) {
            //  alert(data);

            debugger;
            var datavalue = data;
            var myJsonObject = datavalue;
            contentType: "application/json";
            // alert(datavalue);
            // alert(myJsonObject);
            $("#OrderQuantity").attr({ max: myJsonObject, placeholder: myJsonObject });
        },
        error: function (xhr) {
            alert(xhr.responseText);
        }
    });

});




    </script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WinForms/InventoryProject(Validation is done)/InventoryProject/Views/Home/Sent.cshtml
@{
    ViewBag.Title = "Sent";
}

<h2>Your message has been sent</h2>