WinForms/EmployeeForm In Api(half way)/Models/EmployeeContext.cs
namespace EmployeeForm_In_Api.Models
{
    using System;
    using System.Data.Entity;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    public partial class EmployeeContext : DbContext
    {
        public EmployeeContext()
            : base("name=EmployeeContext")
        {
        }
        public DbSet<EmployeeData> employeeData { get; set; }

        public DbSet<Designation> designationName { get; set; }

        public DbSet<Ratings> ratings { get; set; }

        public DbSet<Skills> skills { get; set; }

        public DbSet<SkillTypes> skilltype { get; set; }


        public class ToDoDbCreator : DropCreateDatabaseIfModelChanges<EmployeeContext>
        {

        }
    }
}

WinForms/EmployeeForm In Api(half way)/Models/EmployeeSummery.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EmployeeForm_In_Api.Models
{
    public class EmployeeSummery
    {
        [Key]
        public int SummeryID { get; set; }
        public int EmployeeID { get; set; }
        public int RatingsID { get; set; }
        public int SkillID { get; set; }
       

        public Ratings Ratings { get; set; }
        public Skills Skills { get; set; }
        public EmployeeData EmployeeData { get; set; }
    }
}

WinForms/EmployeeForm In Api(half way)/Controllers/EmployeeApiController.cs
using EmployeeForm_In_Api.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace EmployeeForm_In_Api.Controllers
{
    [Route("api/[controller]")]
    public class EmployeeApiController : ApiController
    {
        //EmployeeData data = new EmployeeData();

        EmployeeContext Db = new EmployeeContext();

        [HttpPost]
        public void PostPersonalDetails([FromBody] EmployeeData data)
        {
           Db.employeeData.Add(new EmployeeData { EmployeeName = data.EmployeeName , Email = data.Email, DesignationID = data.DesignationID});
           Db.SaveChanges();
            
        }

        [HttpGet]       
        public IEnumerable<Designation> GetDesignation()
        {
           /* List<Designation> li = Db.designationName.ToList()*/;
            return Db.designationName.ToList();

        }

        [ActionName("GetRatings")]
        public IEnumerable<Ratings> GetRatings(int id)
        {
            List<Ratings> li = Db.ratings.Where(x => x.SkillTypeID == 1).ToList();            
            return li;
        }

        [ActionName("GetSkillNames")]
        public IEnumerable<Skills> GetSkillNames(int id)
        {
            List<Skills> li = Db.skills.Where(x => x.SkillTypeID == 1).ToList();
            return li;


        }
        [ActionName("GetTechRatings")]
        public IEnumerable<Ratings> GetTechRatings(int id)
        {
            var li = Db.ratings.Where(x => x.SkillTypeID == 2).ToList();
            return li;


        }
        [ActionName("GetTechSkillNames")]
        public IEnumerable<Skills> GetTechSkillNames(int id)
        {
            var li = Db.skills.Where(x => x.SkillTypeID == 2).ToList();
            return li;
        }

    }
}

WinForms/EmployeeForm In Api(half way)/Controllers/EmployeeFormController.cs
using EmployeeForm_In_Api.Models;
using EmployeeForm_In_Api.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmployeeForm_In_Api.Controllers
{

    public class EmployeeFormController : Controller
    {
        int pageCounter;
        // GET: EmployeeForm
        EmployeeData data = new EmployeeData();
        EmployeeContext Db = new EmployeeContext();

        // EmployeeApiController Api = new EmployeeApiController();

        public ActionResult Index()
        {
            // Db.employeeData.Add(new EmployeeData { EmployeeName = "hi" });
            //Db.SaveChanges();
            //ViewBag.designationList = new SelectList(Api.GetDesignation(), "DesignationID", "DesignationName");

            return View();
        }
        public ActionResult Selectskills()
        {
            pageCounter = 1;
            Session["pageCounter"] = 1;
            return View();
        }




        public ActionResult DeveloperSkills()
        {

            //-------------------- either take ratinglist or change the view to get selected radio button ---------
            EmployeeContext sn = new EmployeeContext();
            EmployeeViewModel vm = new EmployeeViewModel();

            pageCounter = Convert.ToInt32(Session["pageCounter"]);

            vm.Skillslist = Db.skills.Where(x => x.SkillID == pageCounter).ToList();

            Session["pageCounter"] = ++pageCounter;


            int totalCount = sn.skills.Where(x =>x.SkillTypeID==1).Count();

            if (pageCounter > totalCount + 2)
            {
                return RedirectToAction("Selectskills");
            }

            return View(vm);

        }






        public ActionResult TechnicalSkills()
        {
            EmployeeContext sn = new EmployeeContext();
            EmployeeViewModel vm = new EmployeeViewModel();
            pageCounter = 6;
            Session["pageCounter"] = 6;

            pageCounter = Convert.ToInt32(Session["pageCounter"]);

            vm.Skillslist = Db.skills.Where(x => x.SkillID == pageCounter).ToList();

            Session["pageCounter"] = ++pageCounter;


            int totalCount = sn.skills.Count();

            if (pageCounter > totalCount + 1)
            {
                return RedirectToAction("Selectskills");
            }

            return View(vm);

        }
      
        public ActionResult Summery( )
        {
            return View();
        }
    }
}

WinForms/EmployeeForm In Api(half way)/Views/EmployeeForm/DeveloperSkills.cshtml
@model EmployeeForm_In_Api.Models.ViewModel.EmployeeViewModel
@{
    ViewBag.Title = "DeveloperSkills";
}

<h2>DeveloperSkills</h2>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script type="text/javascript">

    $(document).ready(function () {
        alert("hi");
        $.ajax({
            type: "GET",
            url: "http://localhost:63333/api/EmployeeApi/GetRatings/1", //URI

            dataType: "json",
            success: function (data) {
                //  alert(data);

                debugger;
                var datavalue = data;
                var myJsonObject = datavalue;
                contentType: "application/json";
                // alert(datavalue);
                // alert(myJsonObject);

                $.each(myJsonObject, function (i, mobj) {
                    //alert(mobj.RatingNames);

                    $("#radio").append('<br> <label> <input type="radio" name="optradio" value="' + mobj.RatingsID + '">' + mobj.RatingNames + '</label>');


                });

            },
            error: function (xhr) {
                alert(xhr.responseText);
            }
        });
        alert("hello");
    });






    $(document).ready(function () {
        alert("hi");
        $.ajax({
            type: "GET",
            url: "http://localhost:63333/api/EmployeeApi/GetSkillNames/1", //URI

            dataType: "json",
            success: function (data) {
                //  alert(data);

                debugger;
                var datavalue = data;
                var myJsonObject = datavalue;
                contentType: "application/json";
                // alert(datavalue);
                // alert(myJsonObject);

                $.each(myJsonObject, function (i, mobj) {
                    
         
               });

                },
                    error: function (xhr) {
                        alert(xhr.responseText);
                    }
            });
        alert("hello");
    });

</script>

<script type="text/javascript">
    $(function () {

        $('#Dev_SubmitButton').click(function () {

            var checkedradio = $('[name="optradio"]:radio:checked').val();

            $("#para").html("Selected Value: " + checkedradio);

        });

    });
</script>

<p id="para"></p>
@foreach (var nm in Model.Skillslist)
{
    <div id="skillname">
       
        @Html.Label(nm.SkillNames, new { id = nm.SkillID})
    </div>

}
<div id="radio">
 
</div>

     @using (Ajax.BeginForm("DeveloperSkills", "EmployeeForm", new AjaxOptions { HttpMethod = "Post", InsertionMode = InsertionMode.Replace, UpdateTargetId = "skillname" }))
    {
        <input id="Dev_SubmitButton" type="submit" value="submit" />
     }

WinForms/EmployeeForm In Api(half way)/Views/EmployeeForm/Index.cshtml
@{
    ViewBag.Title = "Index";
}





<div class="container">
    <h2>Login Form</h2>
@using (Html.BeginForm("Selectskills", "EmployeeForm", FormMethod.Post))
    {
       
        <div class="form-group">
            <label for="Name">NAME:</label>
            <input type="text" class="form-control" id="name" placeholder="Enter NAME">
        </div>
        <div class="form-group">
            <label for="email">Email:</label>
            <input type="Email" class="form-control" id="Email" placeholder="Enter Email">
        </div>
        <div>
            <label>Select Designation :</label>
            <select class="form-control" id="designationList">
                <option selected="selected">Select</option>
            </select>
        </div>
    //  @Html.DropDownList("designationList", "Select Designation")

        <button type="Submit" class="btn btn-default" onclick="add_details()">Login</button>

   
    }
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script type="text/javascript">
   
    function add_details()
        {
            $.ajax({
                type: "POST", //HTTP POST Method
                url: "http://localhost:63333/api/EmployeeApi",
                data: { //Passing data
                    EmployeeName: $("#name").val(), //Reading text box values using Jquery
                    Email: $("#Email").val(),
                    DesignationID: $("#designationList").val(),
                   
                }
            });
            alert("hi");
    }

    $(document).ready(function () {

        $.ajax({
            type: "GET",
            url: "http://localhost:63333/api/EmployeeApi", //URI

            dataType: "json",
            success: function (data) {
                //  alert(data);

                debugger;
                var datavalue = data;
                var myJsonObject = datavalue;
                contentType: "application/json";
                // alert(datavalue);
                // alert(myJsonObject);

                $.each(myJsonObject, function (i, mobj) {
                    alert(mobj.DesignationName);
                    $("#designationList").append('<option value="'+mobj.DesignationID+'">' + mobj.DesignationName + '</option>');

                });

            },
            error: function (xhr) {
                alert(xhr.responseText);
            }
        });

    });
    


</script>

  
       
   

WinForms/EmployeeForm In Api(half way)/Views/EmployeeForm/Selectskills.cshtml
@{
    ViewBag.Title = "Selectskills";
}

<h2>Selectskills</h2>

<div class="SelectSkills" style="text-align: center;border:1px solid ;margin: 0px 280px;padding: 50px;">
    <div class="container">
        <div class="row">  
                <button type="button" onclick="location.href='@Url.Action("DeveloperSkills", "EmployeeForm")'"  style="font-size: 25px;padding: 25px 80px">Developer Skills</button>
            </div>
            <div class="row">
                <button type="button" onclick="location.href='@Url.Action("TechnicalSkills", "EmployeeForm")'"  style="font-size: 25px;padding: 25px 85px;margin-top: 30px;">Technical Skills</button>
            </div>
        </div>
    </div>