Django/website/music/urls.py
from django.conf.urls import url
from . import views
app_name = 'music'

urlpatterns = [
    # url(r'^$', views.index, name = 'index'),
	# url(r'^(?P<album_id>[0-9]+)$', views.detail, name = 'detail'),
   	
	url(r'^$', views.IndexView.as_view(), name = 'index'),
	url(r'^(?P<pk>[0-9]+)$', views.DetailView.as_view(), name = 'detail'),
	
	url(r'^album/add/$', views.AlbumCreate.as_view(), name = 'album-add'),
	url(r'^album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name = 'album-update'),
	url(r'^album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name = 'album-delete'),
]

Django/website/website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    url(r'^music/', include('music.urls')),
    url(r'^admin/', admin.site.urls),
	
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/website/company/models.py
from django.db import models

# Create your models here.

Django/website/music/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Album(models.Model):
	artist = models.CharField(max_length = 200)
	title = models.CharField(max_length = 200)
	genre = models.CharField(max_length = 200)
	album_logo = models.FileField()
	# album_logo = models.CharField(max_length = 1000)
	
	def get_absolute_url(self):
		return reverse('music:detail', kwargs={'pk': self.pk})
	
	def __str__(self):
		return self.title
	
class song(models.Model):
	album = models.ForeignKey(Album, on_delete=models.CASCADE)
	file_type = models.CharField(max_length = 10)
	song_title = models.CharField(max_length = 250)
	
	def __str__(self):
		return self.song_title

Django/website/company/views.py
from django.shortcuts import render

# Create your views here.

Django/website/music/views.py
from django.views import generic
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.core.urlresolvers import reverse_lazy
from . models import Album

# from django.shortcuts import render
# from django.http import HttpResponse
# from django.template import loader
# from . models import Album
# from django.http import Http404
# def index(request):
	# all_albums = Album.objects.all()
	# # html=''
	# # for album in all_albums:
		# # url = '' + str(album.id) + ''
		# # html += '<a href = "'+ url + '">' + album.title + '</a><br>'


	# #################################     either you can use "load" or "render"	     ################################33
	# # template = loader.get_template('index.html')
	# # context={
		# # 'all_albums' : all_albums,
	# # }
	# # return HttpResponse(template.render(context,request))
	# return render(request,'index.html', {'all_albums':all_albums})
	
# def detail(request, album_id):
	# try:
		# album = Album.objects.get(pk = album_id)
	# except Album.DoesNotExist:
		# raise Http404("album doesnot exist")
	# return render(request, 'detail.html', {'album': album})

class IndexView(generic.ListView):
	template_name = 'index.html'
	context_object_name = 'all_album'	
	def get_queryset(self):
		return Album.objects.all()
	
class DetailView(generic.DetailView):
	model = Album
	template_name = 'detail.html'
		
		
class AlbumCreate(CreateView):
	model = Album
	template_name = 'album_form.html'
	fields = ['artist','title','genre','album_logo']
		
class AlbumUpdate(UpdateView):
	model = Album
	template_name = 'album_form.html'
	fields = ['artist','title','genre','album_logo']		
		
class AlbumDelete(DeleteView):
	model = Album
	# = 'album_form.html'
	success_url = reverse_lazy('music:index')		
		
		
		
		
		
		
		
		
		
		
		

Django/website/music/templates/album_form.html
{% extends 'base.html' %}

{% block body %}
<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{% include 'form-template.html' %}
	<button type="submit">submit</button>
{% endblock %}

Django/website/music/templates/base.html
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>viberr</title>
  {% load staticfiles %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>

<body>
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="{% url 'music:index' %}">Viberr</a>
    </div>
	
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active">
		 <a href="{% url 'music:index' %}"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>Albums
		 </a>
		</li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-music" aria-hidden="true"></span>Songs 
		  </a>       
        </li>   
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'music:album-add' %}"><span class="glyphicon glyphicon-plus"></span> Add Album</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-log-off"></span> Logout</a></li>
      </ul>
    </div>
  </div>
</nav>

{% block body %}
{% endblock %}
</body>
</html>

Django/website/music/templates/detail.html
{% extends 'base.html' %}

{% block body %}

	<img src="{{album.album_logo.url}}">

	<h1>{{album.title}}</h1>
	<h3>{{album.artist}}</h3>

	<ul>
		{% for song in album.song_set.all %}
			<li>{{ song.song_title }} -  {{song.file_type}}</li>
		{% endfor %}
	</ul>

{% endblock %}

Django/website/music/templates/form-template.html
{% for field in form %}
<label>{{field.label_tag}}</label>
<div>{{ field }}</div>

{% endfor %}

Django/website/music/templates/index.html
{% extends 'base.html '%}

{% block body %}

<!-- whenever you are using Indexview that time by default you have to use object_list else mention in context name  -->
{% if all_album %}
	<ul>
		{% for album in all_album %}
		
		<!-- details -->
			<!-- <li><a href="/music/{{album.id}}">{{album.title}}</a></li> -->
			<li><a href="{% url 'music:detail' album.id %}">{{album.title}}</a></li>
			
			<form action="{% url 'music:album-delete' album.id  %}" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<button type="submit">
				<span class="glyphicon glyphicon-trash"></span>
			<button>
			{% endfor %}
	</ul>
{% else %}
	<h3>you don't have any album</h3>
{% endif %}

{% endblock %}