Django/cci(Teams)/main/urls.py
from django.conf.urls import url
from . import views
app_name = 'main'

urlpatterns = [
        url(r'^$', views.IndexView.as_view(), name='index'),
        url(r'^(?P<pk>[0-9]+)$', views.DetailView.as_view(), name='details'),
        url(r'^main/add/$', views.TeamMemberCreate.as_view(), name='TeamMember'),
        url(r'^main/(?P<pk>[0-9]+)/delete/$', views.TeamMemberDelete.as_view(), name = 'TeamMember-delete'),
        url(r'^main/teams/add/$', views.TeamsCreate.as_view(), name='Teams'),
        url(r'^main/teams/(?P<pk>[0-9]+)$', views.TeamDetailView.as_view(), name='TeamDetails'),
        url(r'^main/teams/$', views.TeamView.as_view(), name='AllTeams'),
        url(r'^main/(?P<pk>[0-9]+)/teams/delete/', views.TeamsDelete.as_view(), name = 'Teams-delete'),
        ]

Django/cci(Teams)/main/models.py
from django.db import models
from django.core.urlresolvers import reverse


class TeamMembers(models.Model):
    Name = models.CharField(max_length = 200)
    DOB = models.DateField(max_length = 8)
    Designation = models.CharField(max_length = 200)
    Pic = models.FileField()

    def get_absolute_url(self):
        return reverse('main:details', kwargs={'pk': self.pk})

    def __str__(self):
        return self.Name


class Teams(models.Model):
    TeamName = models.CharField(max_length=20)
    TeamLead = models.CharField(max_length=20)
    ClientName = models.CharField(max_length=200)
    Tech = models.CharField(max_length=200)

    def get_absolute_url(self):
        return reverse('main:TeamDetails', kwargs={'pk': self.pk})

    def __str__(self):
        return self.TeamName

Django/cci(Teams)/main/views.py
from django.views import generic
from django.views.generic.edit import CreateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from . models import TeamMembers , Teams


class IndexView(generic.ListView):
    template_name = 'index.html'
    context_object_name = 'all_album'

    def get_queryset(self):
        return TeamMembers.objects.all()


class DetailView(generic.DetailView):
    model = TeamMembers
    context_object_name = 'TeamMembers'
    template_name = 'details.html'


class TeamMemberCreate(CreateView):
    model = TeamMembers
    template_name = 'TeamMember_form.html'
    fields = ['Name', 'DOB', 'Designation', 'Pic']

class TeamMemberDelete(DeleteView):
    model = TeamMembers
    success_url = reverse_lazy('main:index')

class TeamsCreate(CreateView):
    model = Teams
    template_name = 'Teams_form.html'
    fields = ['TeamName', 'TeamLead', 'ClientName', 'Tech']

class TeamDetailView(generic.DetailView):
    model = Teams
    context_object_name = 'TeamsDetail'
    template_name = 'TeamDetails.html'

class TeamView(generic.ListView):
    template_name = 'AllTeams.html'
    context_object_name = 'teams'

    def get_queryset(self):
        return Teams.objects.all()

class TeamsDelete(DeleteView):
    model = Teams
    success_url = reverse_lazy('main:AllTeams')

Django/cci(Teams)/main/templates/AllTeams.html
{% extends 'base.html' %}

{% block body %}

{% if teams %}
	<ul>
		{% for AllTeams in teams %}

		<!-- details -->
			<!-- <li><a href="/music/{{album.id}}">{{album.title}}</a></li> -->
		<div class="container">
			<div class="row">
                <div class="col-sm-12">
		<div class="profile">
        <a href="{% url 'main:TeamDetails' AllTeams.id %}">{{AllTeams.TeamName}}</a>
		<form action="{% url 'main:Teams-delete' AllTeams.id %}" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<button type="submit">
				Delete
			</button>
         </form>
         </div>
        </div>

		</div>
			</div>
	{% endfor %}
	</ul>
{% else %}
	<h3>you don't have any album</h3>
{% endif %}
{% endblock %}

Django/cci(Teams)/main/templates/TeamDetails.html
{% extends 'base.html' %}

{% block body %}

	<h4>TeamName:{{TeamsDetail.TeamName}}</h4>
	<h4>TeamLead:{{TeamsDetail.TeamLead}}</h4>
    <h4>ClientName:{{TeamsDetail.ClientName}}</h4>
    <h4>Tech:{{TeamsDetail.Tech}}</h4>
{% endblock %}

Django/cci(Teams)/main/templates/details.html
{% extends 'base.html' %}

{% block body %}
<img src="{{TeamMembers.Pic.url}}">

	<h4>Name:{{TeamMembers.Name}}</h4>
	<h4>Designation:{{TeamMembers.Designation}}</h4>
    <h4>Date-of-Birth:{{TeamMembers.DOB}}</h4>
{% endblock %}

Django/cci(Teams)/main/templates/form_template.html
{% for field in form %}
<label>{{field.label_tag}}</label>
<div>{{ field }}</div>

{% endfor %}

Django/cci(Teams)/main/templates/index.html
{% extends 'base.html' %}

{% block body %}

{% if all_album %}
	<ul>
		{% for TeamMembers in all_album %}

		<!-- details -->
			<!-- <li><a href="/music/{{album.id}}">{{album.title}}</a></li> -->
		<div class="container">
			<div class="row">
		<div class="profile">
		<img src="{{TeamMembers.Pic.url}}"><br>
        <a href="{% url 'main:details' TeamMembers.id %}">{{TeamMembers.Name}}</a>
		<form action="{% url 'main:TeamMember-delete' TeamMembers.id  %}" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<button type="submit">
				<span class="glyphicon glyphicon-trash"></span>
			</button>
         </form>

        </div>

		</div>
			</div>
	{% endfor %}
	</ul>
{% else %}
	<h3>you don't have any album</h3>
{% endif %}
{% endblock %}